model_name: ViT_S_16

data_root: /home/nju-student/mkh/datasets/ConceptualCaptionsData

imagenet_root: /home/nju-student/mkh/datasets/ImageNet

train:
  batch_size: 256
  num_workers: 4
  lr: 0.01
  epochs: 100
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 10
    mode: min
    min_lr: 0.00001
  loss:
    name: CLIPLoss
  optimizer:
    name: Adam
    weight_decay: 0.0005